name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX resume
        uses: xu-cheng/latex-action@v3
        with:
          root_file: resume.tex
      - name: convert to .md
        uses: Ender-events/pandoc@master
        with:
          args: '-s -f latex -t markdown -o readme.md resume.tex'
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: PDFresume
          path: resume.pdf
      - name: Compile LaTeX cover letter
        uses: xu-cheng/latex-action@v3
        with:
          root_file: coverletter.tex
      - name: convert to .md
        uses: Ender-events/pandoc@master
        with:
          args: '-s -f latex -t markdown -o coverletter.md coverletter.tex'
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: PDFcoverletter
          path: coverletter.pdf
      - name: Commit pdf & .md
        uses: EndBug/add-and-commit@v9
        with:
          # The name of the user that will be displayed as the author of the commit
          message: Upload Build results.
          
